# blaseRtemplates::easy_install("blaserlab/blaseRtools", "new_or_update")
# blaseRtemplates::easy_install("sqjin/CellChat", "link_from_cache")
# blaseRtemplates::easy_install("CytoExploreR", "link_from_cache")
# blaseRtemplates::easy_install("flowWorkspace", "link_from_cache")
# blaseRtemplates::easy_install("SeuratWrappers", "link_from_cache")
# blaseRtemplates::easy_install("Biostrings", "link_from_cache")
# blaseRtemplates::easy_install("ggvenn", "new_or_update")


suppressPackageStartupMessages(library("conflicted"))
suppressPackageStartupMessages(library("blaseRtools"))
suppressPackageStartupMessages(library("blaseRdata"))
suppressPackageStartupMessages(library("tidyverse"))
suppressPackageStartupMessages(library("monocle3"))
suppressPackageStartupMessages(library("circlize"))
suppressPackageStartupMessages(library("ComplexHeatmap"))
suppressPackageStartupMessages(library("lazyData"))
suppressPackageStartupMessages(library("cowplot"))
suppressPackageStartupMessages(library("RColorBrewer"))
suppressPackageStartupMessages(library("ggrepel"))
suppressPackageStartupMessages(library("ggpubr"))
suppressPackageStartupMessages(library("rstatix"))
suppressPackageStartupMessages(library("CytoExploreR"))
suppressPackageStartupMessages(library("Signac"))
suppressPackageStartupMessages(library("patchwork"))
suppressPackageStartupMessages(library("SeuratWrappers"))
suppressPackageStartupMessages(library("Seurat"))
suppressPackageStartupMessages(library("ggtext"))
suppressPackageStartupMessages(library("CrispRVariants"))
suppressPackageStartupMessages(library("msa"))
suppressPackageStartupMessages(library("GenomicFeatures"))
suppressPackageStartupMessages(library("AnnotationDbi"))
suppressPackageStartupMessages(library("eulerr"))
suppressPackageStartupMessages(library("pander"))


blaseRtemplates::bb_renv_datapkg("/home/OSUMC.EDU/blas02/network/X/Labs/Blaser/Brad/projects/pkc_cxcl8_data/datapkg")

lazyData::requireData("pkc.cxcl8.datapkg")
